### ISSUE TITLE
Doesn't Work !!!

### ISSUE THREAD

**Issue by Suleman-Elahi** [sirLisko/shazamify#2]
There is no Spotify icon on the page... !!!

**Comment by sirlisko** [comment]
You are right.

Unfortunately, Spotify removed unauthenticated calls from their web api https://developer.spotify.com/news-stories/2017/01/27/removing-unauthenticated-calls-to-the-web-api/.

It would be nice adding a *login with Spotify* to the web extension, but it's going to be a bit of work.

**Comment by sirlisko** [comment]
Fixed by https://github.com/sirLisko/shazamify/commit/390a99e89004a7d991ce145e578263b017743393 🎉
